/**
 * Copyright (C) 2010 Sopra (support_movalys@sopra.com)
 *
 * This file is part of Movalys MDK.
 * Movalys MDK is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * Movalys MDK is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 * You should have received a copy of the GNU Lesser General Public License
 * along with Movalys MDK. If not, see <http://www.gnu.org/licenses/>.
 */
//
//  MFBeansKeys.h
//  MFCore
//
//

FOUNDATION_EXPORT NSString *const BEAN_KEY_CONFIGURATION_HANDLER;
FOUNDATION_EXPORT NSString *const BEAN_KEY_CORE_DATA_HELPER;
FOUNDATION_EXPORT NSString *const BEAN_KEY_CORE_DATA_PERSISTENT_STORE;
FOUNDATION_EXPORT NSString *const BEAN_KEY_CORE_DATA_MEMORY_STORE;
FOUNDATION_EXPORT NSString *const BEAN_KEY_CSV_LOADER_HELPER;
FOUNDATION_EXPORT NSString *const BEAN_KEY_BASE_VIEW_MODEL;

FOUNDATION_EXPORT NSString *const BEAN_KEY_WAIT_RUN_INIT;
FOUNDATION_EXPORT NSString *const BEAN_KEY_CORE_DATA_RUN_INIT;
FOUNDATION_EXPORT NSString *const BEAN_KEY_LOAD_FORM_RUN_INIT;
FOUNDATION_EXPORT NSString *const BEAN_KEY_LOAD_VISUAL_CONFIGURATION_RUN_INIT;

FOUNDATION_EXPORT NSString *const BEAN_KEY_MAP_VIEW_CONTROLLER;
FOUNDATION_EXPORT NSString *const BEAN_KEY_WEB_VIEW_CONTROLLER;
FOUNDATION_EXPORT NSString *const BEAN_KEY_CREATE_EMAIL_VIEW_CONTROLLER;

FOUNDATION_EXPORT NSString *const BEAN_KEY_FIELD_DESCRIPTOR;
FOUNDATION_EXPORT NSString *const BEAN_KEY_SECTION_DESCRIPTOR;
FOUNDATION_EXPORT NSString *const BEAN_KEY_FORM_DESCRIPTOR;
FOUNDATION_EXPORT NSString *const BEAN_KEY_GROUP_DESCRIPTOR;
FOUNDATION_EXPORT NSString *const BEAN_KEY_WORKSPACE_DESCRIPTOR;
FOUNDATION_EXPORT NSString *const BEAN_KEY_COLUMN_DESCRIPTOR;

FOUNDATION_EXPORT NSString *const BEAN_KEY_READER_FORM;
FOUNDATION_EXPORT NSString *const BEAN_KEY_READER_SECTION;
FOUNDATION_EXPORT NSString *const BEAN_KEY_READER_WORKSPACE;
FOUNDATION_EXPORT NSString *const BEAN_KEY_READER_COLUMN;

FOUNDATION_EXPORT NSString *const BEAN_KEY_URL;
FOUNDATION_EXPORT NSString *const BEAN_KEY_PROPERTY;
FOUNDATION_EXPORT NSString *const BEAN_KEY_BINDING_COMPONENT_DESCRIPTOR;
FOUNDATION_EXPORT NSString *const BEAN_KEY_FORM_EXTEND;

FOUNDATION_EXPORT NSString *const BEAN_KEY_EXTENSION_KEYBOARDING_UI_CONTROL;
FOUNDATION_EXPORT NSString *const BEAN_KEY_EXTENSION_KEYBOARDING_UI_CONTROL_WITH_REG_EXP;

FOUNDATION_EXPORT NSString *const BEAN_KEY_BASE_COMPONENT;
FOUNDATION_EXPORT NSString *const BEAN_KEY_TEXT_FIELD;
FOUNDATION_EXPORT NSString *const BEAN_KEY_LABEL;

FOUNDATION_EXPORT NSString *const BEAN_KEY_POSITION_VIEW_MODEL;

FOUNDATION_EXPORT NSString *const BEAN_KEY_KEYNOTFOUND;

FOUNDATION_EXPORT NSString *const BEAN_KEY_ACTION_GENERIC_LOAD_DATA;

FOUNDATION_EXPORT NSString *const BEAN_KEY_VIEW_MODEL_CREATOR;

FOUNDATION_EXPORT NSString *const BEAN_KEY_FORM_SEARCH_DELEGATE;
FOUNDATION_EXPORT NSString *const BEAN_KEY_FORM_SEARCH_EXTEND;

FOUNDATION_EXPORT NSString *const BEAN_KEY_EXCEPTION;

FOUNDATION_EXPORT NSString *const BEAN_KEY_BINDING;

FOUNDATION_EXPORT NSString *const BEAN_KEY_SECURITY_HELPER;

